; Maximum size of an uploaded file
upload_max_filesize = 512M

; Maximum size of POST data (must be >= upload_max_filesize)
post_max_size = 512M

; Maximum memory a script can consume (should be > post_max_size)
memory_limit = 512M

; Maximum execution time for each script (in seconds)
max_execution_time = 300

; Maximum time for parsing input data (POST, GET, file uploads)
max_input_time = 300